name = "api"
main = ".output/server/index.mjs"
workers_dev = true
account_id = "ee327081b61038e42bdcf0fb83953e38"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "STORAGE"
id = "858ad8a86ee24485bd9455a6696ae194"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }
